wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.22
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.1
    t:
      3:
      - 2
      4: 3.7.1
      5: 0.10.22
      8:
      - 3
      - 5
